FROM shatu/pytorch:torch131_cuda101-onnxrt05_feb5apex_deepspeed2

RUN pip uninstall -y deepspeed

ENV TMP_DIR=/tmp/ds
RUN mkdir -p ${TMP_DIR}

RUN git clone https://github.com/microsoft/DeepSpeed.git ${TMP_DIR}/DeepSpeed
RUN cd ${TMP_DIR}/DeepSpeed && \
    git checkout . && \
    git checkout 1afca8f && \
    ./install.sh --allow_sudo --deepspeed_only 
RUN rm -rf ${STAGE_DIR}/DeepSpeed
RUN python -c "import deepspeed; print(deepspeed.__version__)"
